respostas_app/config/routes.rb
Rails.application.routes.draw do
  resources :produtos
  resources :home
  resources :importantes
  resources :menu
  resources :diagrama
  root :to => 'home#index'

end

respostas_app/app/models/produto.rb
class Produto < ActiveRecord::Base
end

respostas_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

respostas_app/app/controllers/diagrama_controller.rb
class DiagramaController < ApplicationController

  #Exibir Imagem do diagrama
  def index
  end

end

respostas_app/app/controllers/home_controller.rb
class HomeController < ApplicationController
 
  # Pagia inicial
  def index
  end

end

respostas_app/app/controllers/importantes_controller.rb
class ImportantesController < ApplicationController
  
  # Lista de produtos em ordem alfabetica 
  def index
	@produtos = Produto.all.order("item")
  end

end

respostas_app/app/controllers/menu_controller.rb
class MenuController < ApplicationController
  
  # Menu da Aplicacao Lista de Compras
  def index
  end
end

respostas_app/app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all.order("item")
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto was successfully created.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto was successfully updated.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:item, :importante)
    end
end

respostas_app/app/helpers/application_helper.rb
module ApplicationHelper
end

respostas_app/app/helpers/diagrama_helper.rb
module DiagramaHelper
end

respostas_app/app/helpers/home_helper.rb
module HomeHelper
end

respostas_app/app/helpers/importantes_helper.rb
module ImportantesHelper
end

respostas_app/app/helpers/menu_helper.rb
module MenuHelper
end

respostas_app/app/helpers/produtos_helper.rb
module ProdutosHelper
end

respostas_app/app/views/diagrama/index.html.erb
<h1>Diagrama Relacional</h1></br>

<%= image_tag "diagrama.jpg" %></br>

<%= link_to "Voltar para Home", home_index_path %>

respostas_app/app/views/home/index.html.erb
<h1>Respostas App</h1>
<h3>por Valdecir Victor Junior</h3>

<p>
	Escolha um dos Problemas:
   <ul>
      <li>
	<%= link_to "Problema 1", diagrama_index_path %>
      </li>
       <li>
	<%= link_to "Problema 2", menu_index_path %>
       </li>
	<li>	
	<a href="mailto:valdecirvjunior@gmail.com">Feedback por email</a>
	</li>
	</ul>

	
</p>

respostas_app/app/views/importantes/index.html.erb
<h1>Lista de Itens Importantes</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Importante</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @produtos.each do |produto| %>
	<% if produto.importante == "true" %>
	<tr>
        <td><%= produto.item %></td>
        <td><%= produto.importante %></td>
        <td><%= link_to 'Ver', produto %></td>
        <td><%= link_to 'Editar', edit_produto_path(produto) 		%></td>
        <td><%= link_to 'Apagar', produto, method: :delete, data: { confirm: 'Apagar Item?' } %></td>
      </tr>
	<% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Produto', new_produto_path %></br>
<%= link_to 'Menu', menu_index_path %>

respostas_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RespostasApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

respostas_app/app/views/menu/index.html.erb
<h1>Lista de Compras</h1>
<h3>Menu</h3>

<p>
	Escolha uma das ações a seguir:
   <ul>
      <li>
	<%= link_to "Novo Produto", new_produto_path %>
      </li>
      <li>
	<%= link_to "Listar Produtos", produtos_path %>
      </li>
      <li>
	<%= link_to "Listar importantes", importantes_path %>
      </li>
      <li>
	<%= link_to "Voltar para Home", home_index_path %>
       </li>	
   </ul>
	
</p>

respostas_app/app/views/produtos/_form.html.erb
<%= form_for(@produto) do |f| %>
  <% if @produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
      <% @produto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item %><br>
    <%= f.text_field :item %>
  </div>
  <div class="field">
    <%= f.label :importante %><br>
    <%= f.label :importante, "Sim", :value => "sim"  %>
    <%= f.radio_button :importante, true %>
    <%= f.label :favorito, "Não", :value => "nao" %>
    <%= f.radio_button :importante, false, :checked => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

respostas_app/app/views/produtos/edit.html.erb
<h1>Editando produto</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @produto %> |
<%= link_to 'Voltar', produtos_path %>

respostas_app/app/views/produtos/index.html.erb
<h1>Lista de produtos</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Importante</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <td><%= produto.item %></td>
        <td><%= produto.importante %></td>
        <td><%= link_to 'Ver', produto %></td>
        <td><%= link_to 'Editar', edit_produto_path(produto) %></td>
        <td><%= link_to 'Apagar', produto, method: :delete, data: { confirm: 'Apagar Item?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Produto', new_produto_path %></br>
<%= link_to 'Menu', menu_index_path %>
      

respostas_app/app/views/produtos/new.html.erb
<h1>Novo produto</h1>

<%= render 'form' %>

<%= link_to 'Voltar', produtos_path %>

respostas_app/app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @produto.item %>
</p>

<p>
  <strong>Importante:</strong>
  <%= @produto.importante %>
</p>

<%= link_to 'Editar', edit_produto_path(@produto) %> |
<%= link_to 'Voltar', produtos_path %>